apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-sample-deployment
  labels:
    deploy: postgresql-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-sample
  template:
    metadata:
      labels:
        app: postgresql-sample
    spec:
      containers:
      - image: "brusmx/postgresql-python-sample:1.0"
        imagePullPolicy: Always
        name: postgresql-sample
        volumeMounts:
        - name: postgresql-con
          mountPath: "/tmp/postgresql-con"
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: postgresql-con
        secret:
          secretName: postgresql-user-pass            