
default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: <%= ENV['PG_HOST'] %>

development:
  <<: *default


test:
  <<: *default
  database: test

production:
  <<: *default